Repository BostonGosari/Outline, pull requests merged in 2023-11, with the labels that each got.

#160 feature #158 : Onboarding UI 수정 및 기능 개발
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
  Outline/Outline/Source/View/Onboarding/LoginView.swift
  Outline/Outline/Source/ViewModel/InputNicknameViewModel.swift
  Outline/Outline/Source/ViewModel/InputUserInfoViewModel.swift
Labels: ✨ feature, 🎨 design

#162 refactor #154 : 뷰모델 의존성 제거
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/ContentView.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAccuracyManager.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAnalyzeManager.swift
  Outline/Outline/Source/Manager/CourseDataUploadManager.swift
  Outline/Outline/Source/Manager/HealthKitManager.swift
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/Manager/RunningStartManager.swift
  Outline/Outline/Source/Utils/Extension/AnimationExtension.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/Header.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/View/Running/CourseGuideView.swift
  Outline/Outline/Source/View/Running/DigitalTimerView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Running/WorkoutDataView.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/ViewModel/DigitalTimerViewModel.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
  Outline/Outline/Source/ViewModel/RunningMapViewModel.swift
Labels: 🐛 fix, 📁 data, ♻️ Refactor

#168 feat #163 : iOS 30초 미만 러닝 처리
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: ✨ feature, 📱iOS

#170 feat #167 : watchOS 데이터 분기 및 전송
  Outline/Outline Watch/Source/Manager/WatchRunningManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline.xcodeproj/project.pbxproj
Labels: ✨ feature, ⌚️watch, 📁 data, ♻️ Refactor

#166 data #165 : FireStore 누락 데이터 추가
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/Model/Course/CourseModelType.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
Labels: 📁 data

#176 feat #173 : WatchOS 30초 미만 러닝 처리
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/SheetWatchView.swift
Labels: ✨ feature, ⌚️watch

#164 design #155 : Profile 뷰 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/changeProfileImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/changeProfileImage.imageset/changeProfileImage.png
  Outline/Outline/Resource/Image/Image.xcassets/defaultProfileImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/defaultProfileImage.imageset/defaultProfileImage.png
  Outline/Outline/Source/Model/UserInfo/UserInfoModelType.swift
  Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
Labels: 🎨 design

#174 feat #172 : 경로 디테일 뷰 UI 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
Labels: ✨ feature, 📱iOS, 🎨 design

#179 feat #175 : 첫 GPS 아트 러닝 시작시 가이드 화면구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/FirstRunningIcon1.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/FirstRunningIcon1.imageset/FirstRunningIcon1.png
  Outline/Outline/Resource/Image/Image.xcassets/FirstRunningIcon2.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/FirstRunningIcon2.imageset/FirstRunningIcon2.png
  Outline/Outline/Source/View/Running/FirstRunningGuideView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
Labels: ✨ feature, 📱iOS

#185 feat #180 : 동작 및 피트니스 활동 권한요청
  Outline/Outline/Source/ViewModel/InputUserInfoViewModel.swift
Labels: 🛠️ chore, ✨ feature, 📱iOS

#169 refactor #161 : 러닝 기록 뷰 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/View/Record/MapView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
Labels: 🐛 fix, 🎨 design, ♻️ Refactor

#183 feat #182 : OnboardingNotificationAuthView 주석처리
  Outline/Outline/Source/View/Onboarding/OnboardingLocationAuthView.swift
  Outline/Outline/Source/ViewModel/OnboardingLocationAuthViewModel.swift
Labels: ✨ feature

#181 design #177 : runningView 수정
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Running/WorkoutDataView.swift
Labels: 🎨 design

#188 feat #186 : 러닝 데이터 표시, 기록뷰 UI
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/Utils/Extension/DoubleExtension.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Record/RecordHeader.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/View/Running/WorkoutDataView.swift
  Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
Labels: 📁 data

#192 refactor #187 : map 최적화
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/ViewModel/RunningMapViewModel.swift
Labels: 🐛 fix, ♻️ Refactor

#189 feat #178 : 워치에서 러닝 시 iOS에서 시트업
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline/Resource/Image/Image.xcassets/RunningWatch.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/RunningWatch.imageset/RunningWatch.png
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Shared/WatchConnectivityManager.swift
Labels: ✨ feature, ⌚️watch, 📱iOS, 🎨 design

#198 feat #197 : 네트워크 예외 뷰 처리
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
Labels: ✨ feature, 🚨 Hotfix

#191 feature #184 : 둘러보기 UI 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/lookAroundImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/lookAroundImage.imageset/lookAroundImage.png
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/LookAround/LookAroundView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/View/Tab/TabBar.swift
Labels: ✨ feature

#202 feat #139 : Login 기능 추가 구현
  .gitignore
  Outline/GoogleService-Info.plist
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Info.plist
  Outline/Outline/Outline.entitlements
  Outline/Outline/Source/Model/Auth/AppleAuthModel.swift
  Outline/Outline/Source/Model/Auth/AuthModel.swift
  Outline/Outline/Source/Model/Auth/KakaoAuthModel.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/Model/UserInfo/UserInfoModel.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/Onboarding/LoginView.swift
  Outline/Outline/Source/ViewModel/Login/LoginViewModel.swift
Labels: 📁 data

#203 feat #199 : 러닝 시작전 권한 확인 및 분기 처리
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
Labels: ✨ feature, ⌚️watch, 🎨 design

#208 feat #205 : Login, 둘러보기, Profile뷰 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/ContentView.swift
  Outline/Outline/Source/Model/Auth/AppleAuthModel.swift
  Outline/Outline/Source/Model/Auth/AuthModel.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/LookAround/LookAroundView.swift
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
  Outline/Outline/Source/View/Onboarding/LoginView.swift
  Outline/Outline/Source/View/Onboarding/OnboardingNotificationAuthView.swift
  Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/View/Tab/TabBar.swift
  Outline/Outline/Source/ViewModel/InputUserInfoViewModel.swift
  Outline/Outline/Source/ViewModel/Login/LoginViewModel.swift
  Outline/Outline/Source/ViewModel/OnboardingLocationAuthViewModel.swift
  Outline/Outline/Source/ViewModel/ProfileViewModel.swift
Labels: ✨ feature, 📁 data

#233 feat #228 : 이미지 로딩 속도 문제 해결
  Outline/GoogleService-Info.plist
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
Labels: ✨ feature, 📱iOS

#240 design #212 : Profile에서 customFont 적용
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
Labels: 🛠️ chore

#238 feat #237 : 새로운 러닝뷰 UI
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMetricsView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningNavigationView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
Labels: 📱iOS, 🎨 design

#242 fix #241 : 계정 삭제 CoreData 이슈 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/ViewModel/ProfileViewModel.swift
Labels: 🐛 fix

#244 fix #243 : Double Extension에서 fommatedAveragePace 기능 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Utils/Extension/DoubleExtension.swift
Labels: 🐛 fix

#248 feat #245 : 권한 플로우 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/AuthHealth.imageset/AuthHealth.png
  Outline/Outline/Resource/Image/Image.xcassets/AuthHealth.imageset/Contents.json
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Onboarding/HealthAuthView.swift
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
  Outline/Outline/Source/View/Onboarding/NotificationAuthView.swift
  Outline/Outline/Source/View/Onboarding/OnboardingLocationAuthView.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
  Outline/Outline/Source/ViewModel/HealthAuthViewModel.swift
  Outline/Outline/Source/ViewModel/InputNicknameViewModel.swift
  Outline/Outline/Source/ViewModel/Login/LoginViewModel.swift
  Outline/Outline/Source/ViewModel/OnboardingLocationAuthViewModel.swift
Labels: 🐛 fix, ✨ feature

#251 fix #249 : 히어로 애니메이션 수정
  Outline/Outline/Resource/Image/Image.xcassets/OulineLogo.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/OulineLogo.imageset/OulineLogo.png
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: 📱iOS, 🎨 design

#252 feat #247 : NewRunningView 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Manager/RunningStartManager.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMetricsView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: 📁 data

#256 fix #250 : Firebase 이름 변경 에러 수정
  Outline/Outline/Source/ViewModel/ProfileViewModel.swift
Labels: 🐛 fix

#258 feat #239 : 진행률 및 정확도 로직 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAccuracyManager.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAnalyzeManager.swift
  Outline/Outline/Source/View/Accuracy/AccuracyCheckView.swift
  Outline/Outline/Source/View/Accuracy/AccuracyCheckViewModel.swift
Labels: ✨ feature

#260 design #259 : 시트 컴포넌트 화 및 둘러보기 뷰 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/lookAroundImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/lookAroundImage.imageset/lookAroundImage.png
  Outline/Outline/Resource/Image/Image.xcassets/lookAroundImage.imageset/lookArroundImage.png
  Outline/Outline/Source/Manager/RunningStartManager.swift
  Outline/Outline/Source/Utils/Component/GuideToFreeRunningSheet.swift
  Outline/Outline/Source/Utils/Component/NeedLoginSheet.swift
  Outline/Outline/Source/Utils/Component/PermissionSheet.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/LookAround/LookAroundView.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/View/Running/FirstRunningGuideView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: ✨ feature, 📱iOS

#269 fix #268 : userLocation 저장 문제 해결
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/Running/CourseGuideView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: 🐛 fix

#266 feat #264 : 카드 카테고리화 및 Model 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/CourseDataUploadManager.swift
  Outline/Outline/Source/Model/Course/CourseCategoryModelType.swift
  Outline/Outline/Source/Model/Course/CourseModel.swift
  Outline/Outline/Source/Model/Course/CourseModelType.swift
  Outline/Outline/Source/View/CourseCategory/CategoryTestView.swift
  Outline/Outline/Source/View/CourseCategory/CategoryTestViewModel.swift
Labels: ✨ feature, 📁 data

#280 feat #278 : 자유러닝 확인 함수 구현 및 UI 수정
  Outline/Outline/Source/Manager/RunningStartManager.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
Labels: ✨ feature

#274 feat #267 : CoreData Score 추가
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/Model/Score/CourseScoreModel.swift
  Outline/Outline/Source/Model/Score/CourseScoreModelType.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/Model/UserData/UserDataModelType.swift
  Outline/Outline/UserCoreDataModel.xcdatamodeld/UserCoreDataModel.xcdatamodel/contents
Labels: ✨ feature, 📁 data

#277 feat #275 : CourseModel 데이터 수정
  Outline/Outline/Source/Model/Course/CourseModelType.swift
Labels: 📁 data

#281 feat #273 : GPS Art Home View UI 구현 및 데이터 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/Top5/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top1.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top1.imageset/top1.png
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top2.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top2.imageset/top2.png
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top3.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top3.imageset/top3.png
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top4.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top4.imageset/top4.png
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top5.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Top5/top5.imageset/top5.png
  Outline/Outline/Source/Model/Course/CourseModel.swift
  Outline/Outline/Source/View/CourseCategory/CategoryTestView.swift
  Outline/Outline/Source/View/CourseCategory/CategoryTestViewModel.swift
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView1.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView2.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView3.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
Labels: ✨ feature, 📱iOS, 🎨 design

#283 feat #261 : 러닝 완료 완성도에 따른 팝업뷰 UI 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/Finish10.imageset/Finish10.png
  Outline/Outline/Resource/Image/Image.xcassets/Finish100.imageset/Finish100.png
  Outline/Outline/Resource/Image/Image.xcassets/Finish50.imageset/Finish50.png
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/excellent.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/excellent.imageset/exellentStar.png
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/freerun.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/freerun.imageset/free.png
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/great.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/great.imageset/greatStar.png
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/nice.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/nice.imageset/goodStar.png
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/Utils/Component/RunningFinishPopUp.swift
  Outline/Outline/Source/Utils/Component/UnderlineButton.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
Labels: 📱iOS, 🎨 design

#285 fix #279 : 러닝 뷰 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Utils/Extension/FontExtension.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMetricsView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/NewRunning/TransparentBlurView.swift
Labels: 🐛 fix, 🎨 design

#255 feat #231 : Path Manager 최적화 1차
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/View/PathTest/PathTestView.swift
  Outline/Outline/Source/View/Running/CourseGuideView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
Labels: 🐛 fix, ✨ feature

#289 design #288 : ProfileView TTS 토글
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
  Outline/Outline/Source/View/Profile/ProfileVoiceView.swift
Labels: 🎨 design

#294 feat #276 : 공유뷰 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/InstaImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/InstaImage.imageset/InstaImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareBlack.imageset/BlackShareImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareFirstLayer.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareFirstLayer.imageset/ShareTemplate_1.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareSecondLayer.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareSecondLayer.imageset/ShareTemplate_3.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareSelect.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareSelect.imageset/ShareSelect.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareThirdLayer.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareThirdLayer.imageset/ShareTemplate_4.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareVinyl.imageset/WhiteVinylImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite1.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite1.imageset/ShareWhite1.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite2.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite2.imageset/ShareWhite2.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite3.imageset/ShareWhite3.png
  Outline/Outline/Resource/Image/Image.xcassets/Theme1.imageset/Theme1.png
  Outline/Outline/Resource/Image/Image.xcassets/Theme2.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Theme2.imageset/Theme2.png
  Outline/Outline/Source/Utils/Component/PermissionSheet.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImagePickerView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Share/ShareMap.swift
  Outline/Outline/Source/View/Share/ShareView.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
Labels: ✨ feature, 🎨 design, ♻️ Refactor

#291 feat #270 : 워치 디자인 시스템, 네비게이션 UI 추가
  Outline/Outline Watch/Resource/Font/SFProDisplay-Black.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Bold.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Heavy.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Light.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Medium.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Regular.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Semibold.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Thin.otf
  Outline/Outline Watch/Resource/Font/SFProDisplay-Ultralight.otf
  Outline/Outline Watch/Resource/WatchColor.xcassets/0. KeyColor/AccentColor.colorset/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/0. KeyColor/CustomPrimary.colorset/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/0. KeyColor/CustomQuanternary.colorset/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/0. KeyColor/CustomSecondary.colorset/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/0. KeyColor/CustomTertiary.colorset/Contents.json
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/DesignSystem/Component/ElapsedTimeFormatter.swift
  Outline/Outline Watch/Source/DesignSystem/Component/EndRunningSheet.swift
  Outline/Outline Watch/Source/DesignSystem/Component/PermissionSheet.swift
  Outline/Outline Watch/Source/DesignSystem/Component/TwoButtonSheet.swift
  Outline/Outline Watch/Source/DesignSystem/Extension/FontExtension.swift
  Outline/Outline Watch/Source/DesignSystem/Extension/WatchExtension.swift
  Outline/Outline Watch/Source/Manager/WatchRunningManager.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/OutlineWatchApp.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CountDownView.swift
  Outline/Outline Watch/Source/View/CourseDetailView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/ElapsedTimeView.swift
  Outline/Outline Watch/Source/View/EmptyContentView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/MetricsView.swift
  Outline/Outline Watch/Source/View/NavigationTabView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline-Watch-App-Info.plist
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Info.plist
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Model/Course/CourseModelType.swift
  Outline/Shared/WatchConnectivityManager.swift
Labels: ✨ feature, ⌚️watch

#296 feat #287 : 홈뷰 스코어 표시
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/notyet.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ScoreStar/notyet.imageset/notyet.png
  Outline/Outline/Source/Model/Course/CourseModel.swift
  Outline/Outline/Source/Model/Score/CourseScoreModel.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/Model/UserInfo/UserInfoModel.swift
  Outline/Outline/Source/Utils/Component/RunningFinishPopUp.swift
  Outline/Outline/Source/Utils/Component/ScoreStar.swift
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView1.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView2.swift
  Outline/Outline/Source/View/GPSArtHome/MiniScrollView3.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
Labels: ✨ feature, 📱iOS

#295 design #290 : GPSArtDetailCardView UI 수정
  Outline/Outline/Source/Utils/Extension/DoubleExtension.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
Labels: 🎨 design

#300 feat #299 : detail 지도뷰 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Model/Place.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailMap.swift
Labels: ✨ feature

#302 feat #298 : 기록 홈뷰, 기록 그리드뷰 ui 및 정렬, 필터링 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/sampleMapImage.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/sampleMapImage.imageset/Mask group.png
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/Utils/Component/Card/SmallCarouselCard.swift
  Outline/Outline/Source/Utils/Component/Card/SmallListCard.swift
  Outline/Outline/Source/Utils/Extension/FontExtension.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/Record/RecordGridView.swift
  Outline/Outline/Source/View/Record/RecordHeader.swift
  Outline/Outline/Source/View/Record/RecordView.swift
Labels: ✨ feature, 📱iOS, 🎨 design

#304 hotfix #303 : 계정생성시 이름 추가 에러 수정
  Outline/Outline/Source/View/Onboarding/HealthAuthView.swift
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/ViewModel/InputNicknameViewModel.swift
Labels: 🚨 Hotfix

#307 feat #306 : 러닝 결과뷰 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Info.plist
  Outline/Outline/Resource/Font/StretchPro.otf
  Outline/Outline/Resource/Font/StretchPro.ttf
  Outline/Outline/Source/Utils/Component/Card/BigCardBackside.swift
  Outline/Outline/Source/Utils/Extension/FontExtension.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/Share/SharePhotoView.swift
  Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
Labels: ✨ feature, 📱iOS

#320 feat #319 : 투명 랜더링 기능 추가
  Outline/Outline/Source/View/Share/SharePhotoView.swift
Labels: ✨ feature, 📱iOS, 🎨 design

#318 feat #317 : 디테일뷰 수정, 스코어에 따른 카드 연결
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage2.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage2.imageset/FinalImage3.png
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage3.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage3.imageset/FinalImage2.png
  Outline/Outline Watch/Source/Manager/WatchRunningManager.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailMap.swift
  Outline/Outline/Source/View/Record/NewRecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordGridView.swift
  Outline/Outline/Source/View/Record/RecordHeader.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
Labels: ✨ feature, ⌚️watch, 📱iOS, 🎨 design
