Repository BostonGosari/Outline, pull requests merged in 2023-10, with the labels that each got.

#7 add : iOS Color Set 추가
  Outline/Outline/Resource/Color.xcassets/0. KeyColor/Contents.json
  Outline/Outline/Resource/Color.xcassets/0. KeyColor/Fourth.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/0. KeyColor/Primay.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/0. KeyColor/Secondary.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/0. KeyColor/Third.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/1. Opacity/Contents.json
  Outline/Outline/Resource/Color.xcassets/1. Opacity/GrayHeader.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/1. Opacity/GrayTabbar.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray100.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray200.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray300.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray400.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray500.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray600.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray700.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray750.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray800.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/2. Gray/Gray900.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/3. White/Contents.json
  Outline/Outline/Resource/Color.xcassets/3. White/White.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/3. White/White20.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/3. White/White30.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/3. White/White7.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Black.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Black10.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Black20.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Black50.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Black70.colorset/Contents.json
  Outline/Outline/Resource/Color.xcassets/4. Black/Contents.json
Labels: 🛠️ chore

#3 feature #2 : 위치정보 추적 권한 요청
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/View/LocationAuthorizationView.swift
Labels: 📡 API, ✨ feature, ⚙️ setting

#12 feature #9 : 위치기반 추천경로 (1차 PR)
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/DesignSystem/Component/Component.swift
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/View/LocationAuthorizationView.swift
  Outline/Outline/Source/View/RecomendedCourses/RecomendedCourseMap.swift
  Outline/Outline/Source/View/RecomendedCourses/RecommendedCourseView.swift
  Outline/Outline/Source/ViewModel/RecommendedCoursesViewModel.swift
  Outline/Outline/Source/ViewModel/ViewModel.swift
Labels: 📡 API, ✨ feature, 📁 data

#15 design #13 : ColorExtenstion 작성
  Outline/Outline/Source/DesignSystem/Extension/ColorExtension.swift
Labels: 🎨 design

#11 feat #10 : 건강 정보 요청
  Outline/Outline Watch App.entitlements
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Outline.entitlements
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/InputUserInfoView.swift
  Outline/Shared/Logger.swift
  Outline/Shared/WorkoutManager.swift
Labels: 📡 API, ✨ feature

#17 design : GPS Art Home View
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/Image.imageset/logo.png
  Outline/Outline/Resource/Image/Image.xcassets/logo.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/logo.imageset/logo.png
  Outline/Outline/Source/DesignSystem/Component/BackgroundBlur.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Tab/TabView.swift
  Outline/Outline/Source/View/Tab/ViewOffsetKey.swift
Labels: ✨ feature, 🎨 design

#22 feature #1 : FireStore 세팅 및 Model 설계
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Info.plist
  Outline/Outline/Source/GoogleService-Info.plist
  Outline/Outline/Source/Model/CourseModel.swift
  Outline/Outline/Source/Model/CourseModelType.swift
  Outline/Outline/Source/Model/UserModel.swift
  Outline/Outline/Source/Model/UserModelType.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/DataTest/DataTestView.swift
  Outline/Outline/Source/ViewModel/DataTest/DataTestViewModel.swift
Labels: 📑 docs, 📁 data

#29 Feature #26 : RunningView 1차 구현
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/View/RecomendedCourses/RecomendedCourseMap.swift
  Outline/Outline/Source/View/RecomendedCourses/RecommendedCourseView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/ViewModel/RecommendedCoursesViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
Labels: ✨ feature, 🎨 design

#25 feature #14 : 사용자 정보 입력
  Outline/Outline/Source/DesignSystem/Component/Extensions/DateExtention.swift
  Outline/Outline/Source/View/InputUserInfoView.swift
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
  Outline/Outline/Source/ViewModel/InputNicknameViewModel.swift
  Outline/Outline/Source/ViewModel/InputUserInfoViewModel.swift
Labels: ✨ feature, 🎨 design

#21 design : 하단 Carousel View
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Image.xcassets/Sample.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Sample.imageset/Sample.png
  Outline/Outline/Source/DesignSystem/Component/CustomRoundedRectangle.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
Labels: 🎨 design

#28 feature #27 : 러닝중 탭뷰 UI
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Info.plist
  Outline/Outline/Resource/Font/Pretendard-Black.ttf
  Outline/Outline/Resource/Font/Pretendard-Bold.ttf
  Outline/Outline/Resource/Font/Pretendard-ExtraBold.ttf
  Outline/Outline/Resource/Font/Pretendard-Light.ttf
  Outline/Outline/Resource/Font/Pretendard-Medium.ttf
  Outline/Outline/Resource/Font/Pretendard-Regular.ttf
  Outline/Outline/Resource/Font/Pretendard-SemiBold.ttf
  Outline/Outline/Resource/Font/Pretendard-Thin.ttf
  Outline/Outline/Source/ContentView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/CardView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Running/RunningMap.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Running/WorkoutDataView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: ⚙️ setting, 🎨 design

#30 feature #20 : Watch 메인뷰 및 지도 1차 PR
  Outline/GoogleService-Info.plist
  Outline/Outline Watch/Resource/Image/WatchIcon.xcassets/AppIcon.appiconset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchIcon.xcassets/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/AccentColor.colorset/Contents.json
  Outline/Outline Watch/Resource/WatchColor.xcassets/Contents.json
  Outline/Outline Watch/Source/ContentView.swift
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/DesignSystem/Component/WatchComponent.swift
  Outline/Outline Watch/Source/DesignSystem/Extension/WatchExtension.swift
  Outline/Outline Watch/Source/DesignSystem/Modifier/WatchModifier.swift
  Outline/Outline Watch/Source/OutlineWatchApp.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/View.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/DesignSystem/Extension/DateExtention.swift
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
Labels: ✨ feature, ⌚️watch, 🎨 design

#33 feature #26 : 러닝 진행 중 지도 화면 2차 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/KML/duckRun.kml
  Outline/Outline/Resource/KML/test.kml
  Outline/Outline/Source/DesignSystem/Component/RunningPopup.swift
  Outline/Outline/Source/DesignSystem/Extension/FontExtension.swift
  Outline/Outline/Source/Manager/KMLParserManager.swift
  Outline/Outline/Source/View/Running/RunningMap.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/ViewModel/RunningMapViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
Labels: ✨ feature, 🎨 design

#40 chore #38 : 햅틱, 컨페티 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/DesignSystem/Component/Confetti/Confetti.swift
  Outline/Outline/Source/DesignSystem/Component/Confetti/ConfettiShapes.swift
  Outline/Outline/Source/DesignSystem/Component/Confetti/ConfettiView.swift
  Outline/Outline/Source/Manager/HapticManager.swift
Labels: 🛠️ chore, 🎨 design

#43 feature #23 : ERD 기반 CoreData 세팅
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents
  Outline/Outline/CoreUserDataModel.xcdatamodeld/CoreUserDataModel.xcdatamodel/contents
  Outline/Outline/Source/Model/Course/CourseModel.swift
  Outline/Outline/Source/Model/Course/CourseModelType.swift
  Outline/Outline/Source/Model/UserData/PersistentController.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/Model/UserData/UserDataModelType.swift
  Outline/Outline/Source/Model/UserInfo/UserInfoModel.swift
  Outline/Outline/Source/Model/UserInfo/UserInfoModelType.swift
  Outline/Outline/Source/Model/UserModelType.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/DataTest/DataTestView.swift
  Outline/Outline/Source/View/DataTest/UserDataTestView.swift
  Outline/Outline/Source/ViewModel/DataTest/DataTestViewModel.swift
  Outline/Outline/UserCoreDataModel.xcdatamodeld/UserCoreDataModel.xcdatamodel/contents
Labels: ✨ feature, 📁 data

#45 feature #35 : 자유러닝 HomeView
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningMap.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: ✨ feature, 🎨 design

#47 feature #44 : 위도경도 데이터로 Path그리기
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/View/DataTest/PathDrawingTestView.swift
Labels: ✨ feature

#49 feature #48 : Login UI 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Resource/Image/Image.xcassets/loginBackground.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/loginBackground.imageset/loginBackground.jpg
  Outline/Outline/Resource/Image/Image.xcassets/loginLines.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/loginLines.imageset/loginLines.png
  Outline/Outline/Resource/Image/Image.xcassets/logoApple.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/logoApple.imageset/logoApple.png
  Outline/Outline/Resource/Image/Image.xcassets/logoKakaotalk.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/logoKakaotalk.imageset/logoKakaotalk.png
  Outline/Outline/Resource/Image/Image.xcassets/logoOutline.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/logoOutline.imageset/logoOutline.png
  Outline/Outline/Source/ContentView.swift
  Outline/Outline/Source/DesignSystem/Component/CustomRoundedRectangle.swift
  Outline/Outline/Source/View/Onboarding/LoginView.swift
Labels: 🎨 design

#52 feature #46 : 공유 화면 1차 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Model/ShareModel.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImagePickerView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Share/ShareMap.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
Labels: ✨ feature, 🎨 design

#56 feat #32 : 워치 OS HealthKit 관련 데이터 추가, 포멧팅, 뷰 연결, UI 구현
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count1.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count1.imageset/Number1.png
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count2.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count2.imageset/Number2.png
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count3.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/Count3.imageset/Number3.png
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/DesignSystem/Component/ElapsedTimeFormatter.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/ElapsedTimeView.swift
  Outline/Outline Watch/Source/View/MetricsView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline.xcodeproj/project.pbxproj
Labels: ✨ feature, ⌚️watch, 🎨 design, 📁 data

#57 feature #46 : 공유 페이지 2차 구현
  Outline/Outline/Info.plist
  Outline/Outline/Resource/Font/StretchPro.otf
  Outline/Outline/Resource/Image/Image.xcassets/ShareBlack.imageset/BlackShareImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareBlack.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareSelect.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareSelect.imageset/SelectImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareVinyl.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareVinyl.imageset/WhiteVinylImage.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite1.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite1.imageset/ShareWhite1.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite2.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite2.imageset/ShareWhite2.png
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite3.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/ShareWhite3.imageset/ShareWhite3.png
  Outline/Outline/Source/DesignSystem/Component/CardBorder.swift
  Outline/Outline/Source/DesignSystem/Extension/FontExtension.swift
  Outline/Outline/Source/DesignSystem/Modifier/CornerRectangleModifier.swift
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/Model/ShareModel.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
Labels: ✨ feature, 🎨 design

#58 design #42 : Watch 러닝 종료 UI, 달성도별 UI, Sheet 추가
  Outline/Outline Watch/Source/OutlineWatchApp.swift
  Outline/Outline Watch/Source/View/ConfettiWatchView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/FinalWatchView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/SheetWatchView.swift
  Outline/Outline-Watch-App-Info.plist
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/DesignSystem/Modifier/CornerRectangleModifier.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
Labels: ⌚️watch, 🎨 design

#54 feature #51 : KML 데이터 추가 및 FireStore 데이터 세팅
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/KML/seoulDuckRun.kml
  Outline/Outline/Source/Manager/CourseDataUploadManager.swift
  Outline/Outline/Source/View/DataTest/CourseDataUploadView.swift
Labels: 📁 data

#65 feature #60 : WatchOS FireStore & CoreData 연결
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Resource/KML/flightRun.kml
  Outline/Outline/Resource/KML/pohangCrocodileRun.kml
  Outline/Outline/Resource/KML/pohangDangDangRun.kml
  Outline/Outline/Resource/KML/pohangDuckRun.kml
  Outline/Outline/Resource/KML/seoulCamelRun.kml
  Outline/Outline/Resource/KML/seoulDuckRun.kml
  Outline/Outline/Resource/KML/seoulOctopusRun.kml
  Outline/Outline/Resource/KML/test.kml
  Outline/Outline/Source/Model/ConnectingWatchModel.swift
  Outline/Outline/Source/Model/UserData/UserDataModelType.swift
  Outline/Outline/Source/ViewModel/DataTest/DataTestViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
  Outline/Outline/UserCoreDataModel.xcdatamodeld/UserCoreDataModel.xcdatamodel/contents
Labels: 📁 data

#67 fix #66 : 오류 수정
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
Labels: 🚨 Hotfix

#71 data #69 : 러닝 타입 코어데이터 저장
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
Labels: 📁 data

#75 feature #61 : 뷰 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/DesignSystem/Extension/DateExtention.swift
  Outline/Outline/Source/Model/Course/CourseModelType.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningMap.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/MapInfoView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
  Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
  Outline/Outline/UserCoreDataModel.xcdatamodeld/UserCoreDataModel.xcdatamodel/contents
Labels: ✨ feature, 📁 data

#77 feature #63 : Onboarding View 연결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/ContentView.swift
  Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
  Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
  Outline/Outline/Source/View/Onboarding/LoginView.swift
  Outline/Outline/Source/View/Onboarding/OnboardingHealthAuthView.swift
  Outline/Outline/Source/View/Onboarding/OnboardingLocationAuthView.swift
  Outline/Outline/Source/View/Onboarding/OnboardingNotificationAuthView.swift
Labels: 🎨 design

#79 hotfix #78 runningType 누락 오류 해결
  Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
Labels: 🚨 Hotfix

#80 data #74 : 썸네일 변경 및 연결
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/CardView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
Labels: ✨ feature, 📱iOS, 📁 data

#68 feat #64 : 뷰 연결
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline.xcodeproj/project.pbxproj
Labels: ✨ feature

#88 feat #70 기록뷰 및 기록 디테일뷰 ui 구현 및 연결
  Outline/Outline/Source/DesignSystem/Component/BackgroundBlur.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Record/MapView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
Labels: ✨ feature, 🎨 design

#83 design #76 : 러닝 완료 sheet 구현
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: 🎨 design

#95 design : record view ui detail 수정
  Outline/Outline/Source/View/Record/RecordView.swift
Labels: 🎨 design

#90 feature #73 이미지 렌더링
  Outline/Outline/Source/DesignSystem/Extension/ViewExtension.swift
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/OutlineApp.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Share/ShareMap.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
Labels: ✨ feature, 🎨 design

#96 fix #94 : 데이터 오류 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningMap.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
  Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
Labels: 📁 data

#100 design #99 : 탭바 디자인 변경
  Outline/Outline-Watch-App-Info.plist
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/Image/Icon.xcassets/Tab1.imageset/Contents.json
  Outline/Outline/Resource/Image/Icon.xcassets/Tab1.imageset/Tab1.png
  Outline/Outline/Resource/Image/Icon.xcassets/Tab2.imageset/Contents.json
  Outline/Outline/Resource/Image/Icon.xcassets/Tab2.imageset/Tab2.png
  Outline/Outline/Resource/Image/Icon.xcassets/Tab3.imageset/Contents.json
  Outline/Outline/Resource/Image/Icon.xcassets/Tab3.imageset/Tab3.png
  Outline/Outline/Source/Model/TabModel.swift
  Outline/Outline/Source/View/Tab/TabBar.swift
Labels: 📱iOS, 🎨 design

#106 feat #106 : 러닝 종료 확인 alert
  Outline/Outline Watch/Source/View/ControlsView.swift
Labels: ✨ feature, 🎨 design

#116 feature #105 : 미니 가이드 경로 1차 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Resource/KML/test.kml
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/View/Running/CourseGuidView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: ✨ feature, 🎨 design

#117 feature #103 : 데이터 분기 처리
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/CourseDataUploadManager.swift
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Manager/RunningManager.swift
  Outline/Outline/Source/Model/UserData/UserDataModel.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/RecomendedCourses/RecomendedCourseMap.swift
  Outline/Outline/Source/View/RecomendedCourses/RecommendedCourseView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
  Outline/Outline/Source/ViewModel/RecommendedCoursesViewModel.swift
  Outline/Outline/Source/ViewModel/RunningViewModel.swift
Labels: ✨ feature, 📱iOS, 📁 data

#118 feature #105 : 미니 가이드 경로
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/View/Running/CourseGuidView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: ✨ feature, 🎨 design

#126 feat #106 워치 페이스 계산 검토 및 위치/헬스 권한 확인
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/ElapsedTimeView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/MetricsView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Shared/AppDelegate.swift
Labels: 📡 API, ✨ feature, ⌚️watch

#124 design #109 : 러닝 중 뷰 UI 수정
  Outline/Outline/Resource/Image/Image.xcassets/Data.imageset/Contents.json
  Outline/Outline/Resource/Image/Image.xcassets/Data.imageset/Data.png
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: 🎨 design

#125 design #108 : 러닝 완료뷰 UI 수정
  Outline/Outline/Source/Manager/FunctionManager.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningMap.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
Labels: 🎨 design

#119 feature #104 : 이미지 렌더 비율 수정
  Outline/Outline/Source/DesignSystem/Extension/ViewExtension.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Share/ImageShareView.swift
  Outline/Outline/Source/View/Share/ShareMainView.swift
  Outline/Outline/Source/View/Share/ShareMap.swift
Labels: ✨ feature

#121 feat #120 : watch course list의 line cap 수정
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
Labels: 🎨 design

#128 feature #122 : Path gesture 수정
  Outline/Outline/Source/View/Share/ImageShareView.swift
Labels: ✨ feature

#123 feature #101 : 워치 Path, 워치 지도 버튼 수정
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/Manager/WatchPathGenerateManager.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline.xcodeproj/project.pbxproj
Labels: ✨ feature, ⌚️watch

#129 feature #115 : 러닝 시작 전, 러닝 중에서 실시간 유저위치관련 기능
  Outline/Outline/Source/DesignSystem/Component/CountDown.swift
  Outline/Outline/Source/DesignSystem/Component/SlideToUnlock.swift
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Manager/RunningManager.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/CardView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
Labels: ✨ feature, 📱iOS, 📁 data

#132 feature #114 : 경로 정확도 진행도 판별 알고리즘 구현
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAccuracyManager.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAnalyzeManager.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseAnalyzeTest.swift
  Outline/Outline/Source/Manager/CourseAnalyzer/CourseProgressManager.swift
Labels: ✨ feature, 📱iOS, 📁 data

#130 fix #112 : mapKit 수정
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/View/Running/RunningMap.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: 🐛 fix, ✨ feature

#140 fix #135 : 워치 시작 오류 수정
  Outline/Outline Watch/Source/ContentWatchView.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/FinalWatchView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/WatchTabView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/HealthKitManager.swift
Labels: ⌚️watch

#142 feat #134 : GPSArt 홈뷰 수정
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardView.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/Header.swift
Labels: 📱iOS, 🎨 design

#144 feat #143 : 자유러닝 홈뷰 ui detail
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
Labels: 🎨 design

#141 design #138 : Slide to unlock 업데이트
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/DesignSystem/Component/Shimmer.swift
  Outline/Outline/Source/DesignSystem/Component/SlideToUnlock.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
Labels: 📱iOS, 🎨 design

#146 feature #136 : 히어로 애니메이션 최적화
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/DesignSystem/Component/ButtonStyle.swift
  Outline/Outline/Source/DesignSystem/Component/PreferenceKey.swift
  Outline/Outline/Source/DesignSystem/Extension/ViewExtension.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/BigCardView.swift
  Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/GPSArtHome/CardView.swift
  Outline/Outline/Source/View/GPSArtHome/Carousel.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/Header.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
Labels: ✨ feature, 🎨 design

#150 design #147 : watchOS 디자인 수정
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage1.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage1.imageset/FinalImage1.png
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage2.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage2.imageset/FinalImage2.png
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage3.imageset/Contents.json
  Outline/Outline Watch/Resource/Image/WatchImage.xcassets/FinalImage3.imageset/FinalImage3.png
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/ControlsView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/ElapsedTimeView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/MetricsView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
Labels: ⌚️watch, 🎨 design

#157 fix #153 : locationManger 제거 및 map 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/Manager/LocationManager.swift
  Outline/Outline/Source/Manager/RunningManager.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningMap.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningMap.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Running/RunningMap.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Share/CustomShareView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/ViewModel/RunningMapViewModel.swift
Labels: 🐛 fix

#156 Feature/#145 기록뷰 Detail
  Outline/Outline/Source/View/Record/RecordView.swift
Labels: 📱iOS, 🎨 design
