Repository BostonGosari/Outline, pull requests merged in 2024-08, with the labels that each got.

#397 Fix #384 라이브액티비티
  Outline/Outline/Source/Utils/Component/RunningFinishPopUp.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/OutlineLiveActivity/Info.plist
  Outline/OutlineLiveActivity/OutlineLiveActivity.swift
Labels: 🐛 fix, 📱iOS, 🎨 design

#399 Fix #391 아트 컬랙션 개선 및 스냅샷 적용
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline Watch App.xcscheme
  Outline/Outline/Resource/KML/CatRun.kml
  Outline/Outline/Resource/KML/CrocodileRun.kml
  Outline/Outline/Resource/KML/DinosourRun.kml
  Outline/Outline/Resource/KML/DogRun.kml
  Outline/Outline/Resource/KML/DuckRun.kml
  Outline/Outline/Resource/KML/FaceRun.kml
  Outline/Outline/Resource/KML/FishRun.kml
  Outline/Outline/Resource/KML/ParrotRun.kml
  Outline/Outline/Resource/KML/PohangRun.kml
  Outline/Outline/Resource/KML/RoseRun.kml
  Outline/Outline/Resource/KML/SwimmingRun.kml
  Outline/Outline/Resource/KML/WhaleRun.kml
  Outline/Outline/Resource/KML/dangdang.kml
  Outline/Outline/Resource/KML/dragon.kml
  Outline/Outline/Resource/KML/duck.kml
  Outline/Outline/Resource/KML/fish.kml
  Outline/Outline/Resource/KML/fishcat.kml
  Outline/Outline/Resource/KML/flightRun.kml
  Outline/Outline/Resource/KML/moai.kml
  Outline/Outline/Resource/KML/pohangCrocodileRun.kml
  Outline/Outline/Resource/KML/pohangDangDangRun.kml
  Outline/Outline/Resource/KML/seoulCamelRun.kml
  Outline/Outline/Resource/KML/seoulOctopusRun.kml
  Outline/Outline/Resource/KML/test.kml
  Outline/Outline/Resource/KML/건대 오리런.kml
  Outline/Outline/Resource/KML/난지 거북런.kml
  Outline/Outline/Resource/KML/뚝섬 네잎클로버런.kml
  Outline/Outline/Resource/KML/뚝섬 런런.kml
  Outline/Outline/Resource/KML/반포 문어런.kml
  Outline/Outline/Resource/KML/서울과기대 낙타런.kml
  Outline/Outline/Resource/KML/서초 개구리런.kml
  Outline/Outline/Resource/KML/석촌호수 썬글라스런.kml
  Outline/Outline/Resource/KML/성수 댕댕런.kml
  Outline/Outline/Resource/KML/숙대 왈라비런.kml
  Outline/Outline/Resource/KML/신사 댕댕런.kml
  Outline/Outline/Resource/KML/안국 댕댕런.kml
  Outline/Outline/Resource/KML/압구정 댕댕런 테스트 촘촘.kml
  Outline/Outline/Resource/KML/압구정 댕댕런 테스트.kml
  Outline/Outline/Resource/KML/압구정 댕댕런.kml
  Outline/Outline/Resource/KML/올림픽 비행기런.kml
  Outline/Outline/Resource/KML/을지로 새런.kml
  Outline/Outline/Resource/KML/이촌 골프런.kml
  Outline/Outline/Resource/KML/충무 고래런.kml
  Outline/Outline/Source/Utils/Component/Card/SmallCarouselCard.swift
  Outline/Outline/Source/Utils/Component/Card/SmallListCard.swift
  Outline/Outline/Source/Utils/Extension/CoordinateExtension.swift
  Outline/Outline/Source/View/Record/MapSnapshotImageView.swift
  Outline/Outline/Source/View/Record/RecordCardView.swift
  Outline/Outline/Source/View/Record/RecordDetailMapView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordGridView.swift
  Outline/Outline/Source/View/Record/RecordMapView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/View/TestView/MapSnapshotTestView.swift
  Outline/Outline/Source/View/TestView/PathManagerTestView.swift
  Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
Labels: 🐛 fix, ✨ feature

#404 fix #384 : 라이브액티비티 워치에서 비활성화
  Outline/OutlineLiveActivity/OutlineLiveActivity.swift
Labels: 🐛 fix

#405 Fix #386 : 러닝 종료 액션 수정
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/Utils/Component/RunningFinishPopUp.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningMapView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Shared/Manager/LocationManager.swift
Labels: 🐛 fix

#406 Fix #389 : 러닝 완료 후 별 적용 오류 해결
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: 🐛 fix
