Repository BostonGosari/Outline, pull requests merged in 2024-07, with the labels that each got.

#382 Refactor #381 : 파일명 변경
  Outline/Outline Watch/Source/DesignSystem/Modifier/WatchModifier.swift
  Outline/Outline Watch/Source/Model/Model.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/Mirroring/MirroringView.swift
  Outline/Outline/Source/View/Record/RecordDetailMapView.swift
  Outline/Outline/Source/View/Record/RecordDetailView.swift
  Outline/Outline/Source/View/Record/RecordGridView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/View/Running/CourseGuideView.swift
  Outline/Outline/Source/View/Running/FirstRunningGuideView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
  Outline/Outline/Source/View/Running/RunningMetricsView.swift
  Outline/Outline/Source/View/Running/RunningNavigationView.swift
  Outline/Outline/Source/View/Running/RunningView.swift
  Outline/Outline/Source/View/Running/TransparentBlurView.swift
  Outline/Outline/Source/View/Share/ShareView+Extension.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
Labels: ♻️ Refactor

#380 Fix #379 : 홀로그램 오류 수정
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/MotionManager.swift
  Outline/Outline/Source/Utils/Component/Card/BigCard.swift
Labels: 🐛 fix, 🎨 design

#395 Fix #394 : 몸풀기용 간단한 UI 수정 작업
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Outline/Outline/Source/Utils/Component/NeedLoginSheet.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/Record/RecordHeader.swift
  Outline/Outline/Source/View/Record/RecordView.swift
Labels: 🐛 fix, 🛠️ chore, 🎨 design

#396 Fix #385 : 미러링 개선
  Outline/Outline Watch/Source/DesignSystem/Component/ElapsedTime.swift
  Outline/Outline Watch/Source/DesignSystem/Component/ElapsedTimeFormatter.swift
  Outline/Outline Watch/Source/DesignSystem/Component/FinalImage.swift
  Outline/Outline Watch/Source/Manager/WatchRunningManager.swift
  Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
  Outline/Outline Watch/Source/View/CountDownView.swift
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/FinishWatchView.swift
  Outline/Outline Watch/Source/View/MetricsView.swift
  Outline/Outline Watch/Source/View/Mirroring/MirroringControlsView.swift
  Outline/Outline Watch/Source/View/Mirroring/MirroringMapWatchView.swift
  Outline/Outline Watch/Source/View/Mirroring/MirroringMetricsView.swift
  Outline/Outline Watch/Source/View/Mirroring/MirroringNavigationWatchView.swift
  Outline/Outline Watch/Source/View/Mirroring/MirroringTabWatchView.swift
  Outline/Outline Watch/Source/View/Running/ControlsView.swift
  Outline/Outline Watch/Source/View/Running/MapWatchView.swift
  Outline/Outline Watch/Source/View/Running/MetricsView.swift
  Outline/Outline Watch/Source/View/Running/NavigationTabView.swift
  Outline/Outline Watch/Source/View/Running/TabWatchView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline Watch/Source/ViewModel/CourseListWatchViewModel.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline Watch App (Notification).xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline Watch App.xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline.xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/OutlineLiveActivityExtension.xcscheme
  Outline/Outline/Info.plist
  Outline/Outline/Source/Manager/RunningDataManager.swift
  Outline/Outline/Source/View/Mirroring/MirroringView.swift
  Outline/Outline/Source/View/Record/RecordView.swift
  Outline/Outline/Source/ViewModel/GPSArtHomeViewModel.swift
  Outline/Shared/Logger.swift
  Outline/Shared/WatchConnectivityManager.swift
Labels: 🐛 fix, 🛠️ chore, ⌚️watch

#398 Fix #383 : 러닝 경로 보정 알고리즘 구현
  Outline/Outline Watch/Source/View/Mirroring/MirroringMapWatchView.swift
  Outline/Outline Watch/Source/View/Running/MapWatchView.swift
  Outline/Outline/Source/View/Mirroring/MirroringMapView.swift
  Outline/Outline/Source/View/Running/RunningMapView.swift
Labels: 🐛 fix
