Repository BostonGosari/Outline, pull requests merged in 2024-01, with the labels that each got.

#339 refactor #336 : 권한 요청 관련 함수 변경
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/RunningStartManager.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
Labels: ♻️ Refactor

#344 Fix : #337 : 로그인 에러 해결
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Info.plist
  Outline/Outline/Source/Model/Auth/AuthModel.swift
  Outline/Outline/Source/View/Profile/ProfileView.swift
  Outline/Outline/Source/ViewModel/ProfileViewModel.swift
Labels: 🐛 fix

#342 fix #341 : 라이브액티비티 삭제 안되는 문제 해결
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
Labels: 🐛 fix, 📱iOS

#346 feat #343 : 건강 권한 요청
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/Manager/RunningStartManager.swift
Labels: 🐛 fix

#347 fix #338 : MapKit UIKit으로 변경
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/FininshRunning/FinishRunningMapView.swift
  Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
  Outline/Outline/Source/View/FreeRunning/FreeRunningMapView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationMapView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailMap.swift
  Outline/Outline/Source/View/GPSArtHome/CardDetailMapView.swift
  Outline/Outline/Source/View/Mirroring/MirroringMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/Record/NewRecordDetailMapView.swift
  Outline/Outline/Source/View/Record/NewRecordDetailView.swift
Labels: 🐛 fix, ♻️ Refactor

#353 refactor #340 : PathManager 최적화
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/SummaryView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline Watch App (Notification).xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline Watch App.xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/Outline.xcscheme
  Outline/Outline.xcodeproj/xcshareddata/xcschemes/OutlineLiveActivityExtension.xcscheme
  Outline/Outline/Resource/KML/dangdang.kml
  Outline/Outline/Resource/KML/dragon.kml
  Outline/Outline/Resource/KML/duck.kml
  Outline/Outline/Resource/KML/fish.kml
  Outline/Outline/Resource/KML/fishcat.kml
  Outline/Outline/Resource/KML/moai.kml
  Outline/Outline/Source/Manager/PathGenerateManager.swift
  Outline/Outline/Source/Manager/PathManager.swift
  Outline/Outline/Source/Utils/Component/RunningFinishPopUp.swift
  Outline/Outline/Source/Utils/Extension/ArrayExtension.swift
  Outline/Outline/Source/Utils/Extension/CoordinateExtension.swift
  Outline/Outline/Source/Utils/Extension/FontExtension.swift
  Outline/Outline/Source/Utils/Extension/ViewExtension.swift
  Outline/Outline/Source/View/NewRunning/CourseGuideView.swift
  Outline/Outline/Source/View/NewRunning/NewRunningView.swift
  Outline/Outline/Source/View/PathTest/DrawPathView.swift
  Outline/Outline/Source/View/PathTest/PathTestView.swift
  Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
  Outline/Outline/Source/View/Profile/ProfileVoiceView.swift
  Outline/Outline/Source/View/Share/ShareView.swift
  Outline/Outline/Source/View/Tab/HomeTabView.swift
  Outline/Outline/Source/ViewModel/ShareViewModel.swift
Labels: 🐛 fix, ✨ feature, ♻️ Refactor

#357 design #356 : 카드 애니메이션 수정
  Outline/Outline/Source/Utils/Component/Card/BigCard.swift
Labels: 🎨 design

#361 fix #360 : map 오류 수정
  Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
Labels: 🐛 fix

#362 feat #354 : watchOS 맵 오류 수정
  Outline/Outline Watch/Source/View/CourseListWatchView.swift
  Outline/Outline Watch/Source/View/MapWatchView.swift
  Outline/Outline Watch/Source/View/MirroringView/MirroringMapWatchView.swift
  Outline/Outline.xcodeproj/project.pbxproj
  Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
  Outline/Outline/Source/View/Mirroring/MirroringMapView.swift
Labels: 🐛 fix, ✨ feature, 🚨 Hotfix
